config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :accounts
    resources :banks
    resources :snapshots
    resources :users
    resources :wages

    root to: "accounts#index"
  end

  resources :fine_ants
  resource :dashboard do
    get "snapshot-chart-data", to: "dashboards#snapshot_chart_data"
  end

  root to: redirect("/dashboard")
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Administrate::ApplicationHelper

  def namespace
    "admin"
  end

  def nav_link_state(resource)
    if controller.controller_name == "dashboards" && resource == "dashboard"
      :active
    else
      :inactive
    end
  end
end

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <%= link_to "💰🐜🏡", dashboard_path, class: "navigation__link navigation__link--#{nav_link_state("dashboard")}" %>
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      resource_index_route(resource),
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) %>
  <% end %>
</nav>