config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :accounts
    resources :banks
    resources :snapshots
    resources :users
    resources :wages

    root to: "accounts#index"
  end

  resources :fine_ants
  resource :dashboard do
    get "snapshot-chart-data", to: "dashboards#snapshot_chart_data"
  end

  root to: redirect("/dashboard")
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @summaries = AccountSummaries.new(Account.active)
  end

  def snapshot_chart_data
    render json: merge_points([Snapshot.chart_data, Wage.chart_data])
  end

  def merge_points(points)
    points.flatten.group_by { |e| e[:date] }.map { |(_, entries)|
      if entries.size == 1
        entries.first
      else
        entries.each_with_object({}) { |entry, combined|
          combined.merge!(entry)
        }
      end
    }.flatten.sort_by { |e| e[:date] }
  end
end

app/views/dashboards/show.slim
- if flash[:info]
  .flashes
    .flash.flash-notice
      = flash[:info]

header.main-content__header
  h1#page-title.main-content__page-title 💰🐜 Dashboard 📈

#snapshot-chart

table
  thead
    tr
      th Account Name
      th Last Updated
      th YTD Change
      th Monthly Change
      th Weekly Change
      th.total Amount

  tbody
    - @summaries.accounts.each do |summary|
      - next if summary.amount == 0
      tr
        td
          = link_to summary.name, admin_account_path(summary.account)
        td
          = summary.last_updated.strftime("%B %d, %Y")
        td.currency class=(summary.ytd_change.positive? ? 'positive' : 'negative')
          = humanized_money_with_symbol summary.ytd_change
        td.currency class=(summary.month_change.positive? ? 'positive' : 'negative')
          = humanized_money_with_symbol summary.month_change
        td.currency class=(summary.week_change.positive? ? 'positive' : 'negative')
          = humanized_money_with_symbol summary.week_change
        td.currency.total class=('negative' unless summary.amount.positive?)
          = humanized_money_with_symbol summary.amount
  tfoot
    tr
      td colspan=2
        strong Totals
      td.currency class=(@summaries.ytd_change.positive? ? 'positive' : 'negative')
        strong
          = humanized_money_with_symbol @summaries.ytd_change
      td.currency class=(@summaries.month_change.positive? ? 'positive' : 'negative')
        strong
          = humanized_money_with_symbol @summaries.month_change
      td.currency class=(@summaries.week_change.positive? ? 'positive' : 'negative')
        strong
          = humanized_money_with_symbol @summaries.week_change
      td.currency.total class=('negative' unless @summaries.amount.positive?)
        strong
          = humanized_money_with_symbol @summaries.amount

- if @summaries.empty_accounts.any?
  p.fine-print
    | Hiding these accounts, because they're empty: #{@summaries.empty_accounts.map {|s| s.name }.join(", ")}

.actions
  = link_to fine_ants_path, :method => :post do
    .big-update-button Take Fresh Account Snapshots!